/* Autogenerated by hxtools bin2c */
#ifndef RSIMAGES_H
#define RSIMAGES_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_addsupport_png[424];
extern const unsigned char bin2c_aligntobed_png[1328];
extern const unsigned char bin2c_clearbeds_png[466];
extern const unsigned char bin2c_clip_png[1144];
extern const unsigned char bin2c_colour_png[634];
extern const unsigned char bin2c_leftchevron_png[385];
extern const unsigned char bin2c_move_png[304];
extern const unsigned char bin2c_removesupport_png[391];
extern const unsigned char bin2c_rightchevron_png[348];
extern const unsigned char bin2c_rotate_png[607];
extern const unsigned char bin2c_rovalogo_png[15290];
extern const unsigned char bin2c_scale_png[354];
extern const unsigned char bin2c_slice_png[899];
extern const unsigned char bin2c_supportGen_png[353];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* RSIMAGES_H */
