/* Autogenerated by hxtools bin2c */
#ifndef SPLASHSCREEN_H
#define SPLASHSCREEN_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_rssplashscreen_png[74822];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* SPLASHSCREEN_H */
