/* Autogenerated by hxtools bin2c */
#ifndef EULA_H
#define EULA_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_ordterms_txt[91955];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* EULA_H */
